# Generated by Django 3.2.4 on 2021-07-08 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_user', '0002_auto_20210706_0944'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
    ]
