# Generated by Django 3.2.4 on 2021-07-12 16:40

from django.db import migrations


class Migration(migrations.Migration):
    def add_sample_skills(apps, schema_editor):
        Skill = apps.get_model('app', 'Skill')
        skills = [{"name": "Django", "description": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
                   "skill_type": 'Career skill'},
                  {"name": "Python", "description": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
                   "skill_type": 'Career skill'},
                  {"name": "Sass", "description": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
                   "skill_type": 'Career skill'},
                  {"name": "TDD", "description": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
                   "skill_type": 'Career skill'}]
        for skill in skills:
            skill_entry = Skill(name=skill['name'], description=skill['description'], skill_type=skill['skill_type'])
            skill_entry.save()
    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_sample_skills),
    ]
