# Generated by Django 3.2.4 on 2021-07-14 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SkillLevel',
        ),
    ]
