# Generated by Django 3.2.4 on 2021-07-12 17:47

from django.db import migrations


class Migration(migrations.Migration):
    def add_sample_skills_level(apps, schema_editor):
        SkillLevel = apps.get_model('app', 'SkillLevel')
        skills_level = [{"name": "Beginner", "description": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'},
                        {"name": "Intermediate", "description": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'},
                        {"name": "Advanced", "description": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'},
                        {"name": "Expert", "description": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'}]
        for skill_level in skills_level:
            skill_level_entry = SkillLevel(name=skill_level['name'], description=skill_level['description'])
            skill_level_entry.save()

    dependencies = [
        ('app', '0002_auto_20210712_1640'),
    ]

    operations = [
           migrations.RunPython(add_sample_skills_level),
    ]
