# Generated by Django 3.2.4 on 2021-07-14 12:41

from django.db import migrations


def add_skill_levels(apps, schema_editor):
    SkillLevel = apps.get_model('super_admin', 'SkillLevel')
    skill_levels = ['Awareness', 'Working knowledge', 'Practitioner', 'Expert']
    for skill_level in skill_levels:
        s = SkillLevel(name=skill_level)
        s.save()


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0003_skilllevel'),
    ]

    operations = [
        migrations.RunPython(add_skill_levels)
    ]
