# Generated by Django 3.2.4 on 2021-07-21 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
        ('super_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_role_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.skill')),
                ('job_role_skill_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super_admin.skilllevel')),
                ('job_role_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_roles.job')),
            ],
        ),
    ]
