# Generated by Django 3.2.4 on 2021-07-08 11:28

from django.db import migrations


class Migration(migrations.Migration):
    def add_sample_jobs(apps, schema_editor):
        Job = apps.get_model('job_roles', 'Job')
        jobs = ['Junior Developer', 'Mid Developer', 'Senior Developer', 'Lead Developer', 'Head of Development',
                'User Researcher', 'Delivery Manager']
        for job in jobs:
            j = Job(job_title=job)
            j.save(force_insert=True)
    dependencies = [
        ('job_roles', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_sample_jobs)
    ]
