# Generated by Django 3.2.4 on 2021-08-09 10:25

from django.db import migrations, models
import job_roles.validators


class Migration(migrations.Migration):

    dependencies = [
        ('job_roles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_title',
            field=models.CharField(max_length=50, unique=True, validators=[job_roles.validators.validate_input_capitalised]),
        ),
    ]
