# Generated by Django 3.2.4 on 2021-08-09 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
        ('job_roles', '0002_alter_job_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competency',
            name='job_role_skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.skill'),
        ),
    ]
