# Generated by Django 3.2.4 on 2021-07-15 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210712_1747'),
        ('job_roles', '0002_auto_20210708_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_role_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.skill')),
                ('job_role_skill_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.skilllevel')),
                ('job_role_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_roles.job')),
            ],
        ),
    ]
