# Generated by Django 3.2.4 on 2021-07-15 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210712_1747'),
        ('job_roles', '0003_jobrole'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobRole',
            new_name='JobRoles',
        ),
    ]
