# Generated by Django 3.2.4 on 2021-07-16 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210712_1747'),
        ('job_roles', '0004_rename_jobrole_jobroles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobRoles',
            new_name='Competency',
        ),
    ]
