# Generated by Django 3.2.4 on 2021-07-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_roles', '0005_rename_jobroles_competency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
