# Generated by Django 3.2.4 on 2021-06-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='surname',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newuser',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
    ]
