# Generated by Django 3.2.4 on 2021-07-07 12:51

from django.db import migrations, models
import signup.validators


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='groups',
            field=models.ManyToManyField(to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[signup.validators.validate_domain_email]),
        ),
    ]
