# Generated by Django 3.2.4 on 2021-06-30 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20210629_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='hashed_password',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
